# ==============================================================================
# AUTHOR: Jason Phaneuf
# DATE: July 2026
# DESCRIPTION: Install httpd, configure firewalld and start the service.#              
# ==============================================================================
---
- name: Install and start Apache
  hosts: Lab

  tasks:
  - name: Install httpd
    become: yes
    dnf:
      name: httpd
      state: present

  - name: Start httpd
    become: yes
    service:
      name: httpd
      state: started

  - name: Open port 80 for http access
    become: yes
    ansible.posix.firewalld:
      service: http
      permanent: true
      state: enabled

  - name: Restart firewalld service to load firewall changes
    become: yes
    service:
      name: firewalld
      state: reloaded